import type { DayOfWeekName, ExerciseItem, WorkoutPlan } from "../types";

export const WORKOUT_PLANS: WorkoutPlan[] = [
  {
    id: "plan-1",
    name: "Workout Plan 1",
    description: "Strength foundation, chest, triceps, bodyweight circuits, back and shoulders",
    days: {
      Monday: [
        { id: "p1-m-1", order: 1, name: "Inclined bench press", target: "20 X2" },
        { id: "p1-m-2", order: 2, name: "Flat benchpress", target: "20 X2" },
        { id: "p1-m-3", order: 3, name: "Peck deck fly", target: "20 X2" },
        { id: "p1-m-4", order: 4, name: "Cable pushdown (Tricep)", target: "30 X2" },
        { id: "p1-m-5", order: 5, name: "Dumble extension", target: "25 X2" },
        { id: "p1-m-6", order: 6, name: "Dumble kickback", target: "20 X2" },
        { id: "p1-m-7", order: 7, name: "Flying squats", target: "30 X2" },
        { id: "p1-m-8", order: 8, name: "Skipping", target: "200" },
        { id: "p1-m-9", order: 9, name: "5 laps run (Full ground)", target: "5 laps" },
        { id: "p1-m-10", order: 10, name: "Staircase", target: "4 stairs" },
      ],
      Tuesday: [
        { id: "p1-tu-1", order: 1, name: "Skipping", target: "X100" },
        { id: "p1-tu-2", order: 2, name: "Staircase", target: "X1" },
        { id: "p1-tu-3", order: 3, name: "Jumping Jacks", target: "X100" },
        { id: "p1-tu-4", order: 4, name: "High knee jump", target: "X100" },
        { id: "p1-tu-5", order: 5, name: "Pushups", target: "X20" },
        { id: "p1-tu-6", order: 6, name: "Skipping", target: "X100" },
        { id: "p1-tu-7", order: 7, name: "Staircase", target: "X1" },
        { id: "p1-tu-8", order: 8, name: "Jumping Jacks", target: "X100" },
        { id: "p1-tu-9", order: 9, name: "High knee jump", target: "X100" },
        { id: "p1-tu-10", order: 10, name: "Pushups", target: "X20" },
        { id: "p1-tu-11", order: 11, name: "Break", target: "2 mins", durationSeconds: 120, isRest: true },
        { id: "p1-tu-12", order: 12, name: "Skipping", target: "X100" },
        { id: "p1-tu-13", order: 13, name: "Staircase", target: "X1" },
        { id: "p1-tu-14", order: 14, name: "Jumping Jacks", target: "X100" },
        { id: "p1-tu-15", order: 15, name: "High knee jump", target: "X100" },
        { id: "p1-tu-16", order: 16, name: "Pushups", target: "X20" },
        { id: "p1-tu-17", order: 17, name: "2 laps run (full ground)", target: "2 laps" },
        { id: "p1-tu-18", order: 18, name: "Flying squats", target: "X20" },
        { id: "p1-tu-19", order: 19, name: "2 laps run (full ground)", target: "2 laps" },
        { id: "p1-tu-20", order: 20, name: "Flying squats", target: "X20" },
      ],
      Wednesday: [
        { id: "p1-w-1", order: 1, name: "Staircase", target: "X2 (4 floors)" },
        { id: "p1-w-2", order: 2, name: "Lat pull down", target: "25 X2" },
        { id: "p1-w-3", order: 3, name: "Rowing", target: "25 X2" },
        { id: "p1-w-4", order: 4, name: "Cable curl up", target: "30 X2" },
        { id: "p1-w-5", order: 5, name: "Dumbbell Curl up", target: "25 X2" },
        { id: "p1-w-6", order: 6, name: "Dumbbell hammer", target: "25 X2" },
        { id: "p1-w-7", order: 7, name: "2 laps run (full ground)", target: "2 laps" },
        { id: "p1-w-8", order: 8, name: "Flying Squats", target: "X25" },
        { id: "p1-w-9", order: 9, name: "2 laps run (full ground)", target: "2 laps" },
        { id: "p1-w-10", order: 10, name: "Flying Squats", target: "X25" },
        { id: "p1-w-11", order: 11, name: "Side Squats", target: "X20" },
      ],
      Thursday: [
        { id: "p1-th-1", order: 1, name: "Staircase", target: "4 Floors X2" },
        { id: "p1-th-2", order: 2, name: "Skipping", target: "100" },
        { id: "p1-th-3", order: 3, name: "Pushups", target: "20" },
        { id: "p1-th-4", order: 4, name: "Jumping squats", target: "25" },
        { id: "p1-th-5", order: 5, name: "High knee Jump running", target: "2 Round" },
        { id: "p1-th-6", order: 6, name: "Leg raises", target: "40" },
        { id: "p1-th-7", order: 7, name: "On Spot jumping", target: "100" },
        { id: "p1-th-8", order: 8, name: "Laps Running", target: "5 rounds ground" },
        { id: "p1-th-9", order: 9, name: "Jumping squats", target: "25" },
        { id: "p1-th-10", order: 10, name: "On Spot jumping", target: "100" },
        { id: "p1-th-11", order: 11, name: "Staircase", target: "4 Floors X1" },
        { id: "p1-th-12", order: 12, name: "Pushups", target: "25" },
        { id: "p1-th-13", order: 13, name: "Leg raise", target: "40" },
        { id: "p1-th-14", order: 14, name: "Fast Running", target: "5 Rounds" },
        { id: "p1-th-15", order: 15, name: "Jumping squats", target: "25" },
        { id: "p1-th-16", order: 16, name: "High knee Jump walking", target: "2 Round" },
        { id: "p1-th-17", order: 17, name: "On Spot jumping", target: "100" },
        { id: "p1-th-18", order: 18, name: "Pushups", target: "25" },
        { id: "p1-th-19", order: 19, name: "Full ground running", target: "10 rounds" },
        { id: "p1-th-20", order: 20, name: "Leg raise", target: "40" },
        { id: "p1-th-21", order: 21, name: "Jumping squats", target: "25" },
        { id: "p1-th-22", order: 22, name: "Side squats", target: "15" },
      ],
      Friday: [
        { id: "p1-f-1", order: 1, name: "Staircases", target: "4 floors X2" },
        { id: "p1-f-2", order: 2, name: "Dumbbell raise", target: "25 X3 (shoulder)" },
        { id: "p1-f-3", order: 3, name: "Lateral Dumbbell raise", target: "25 X3 (shoulder)" },
        { id: "p1-f-4", order: 4, name: "Front Dumbbell Raise", target: "25 X3 (shoulder)" },
        { id: "p1-f-5", order: 5, name: "Reverse Peck deck fly", target: "25 X2 (shoulder)" },
        { id: "p1-f-6", order: 6, name: "Jumping Squats", target: "100" },
        { id: "p1-f-7", order: 7, name: "Calf Raise", target: "50" },
        { id: "p1-f-8", order: 8, name: "Walking Lunges", target: "200" },
        { id: "p1-f-9", order: 9, name: "Leg Curl", target: "25 X3" },
      ],
    },
  },
  {
    id: "plan-2",
    name: "Workout Plan 2",
    description: "Progressive volume, stair conditioning, elliptical intervals, and leg supersets",
    days: {
      Monday: [
        { id: "p2-m-1", order: 1, name: "Staircase", target: "4 Floors X2" },
        { id: "p2-m-2", order: 2, name: "Inclined benchpress", target: "15 X3" },
        { id: "p2-m-3", order: 3, name: "Flat benchpress", target: "15 X3" },
        { id: "p2-m-4", order: 4, name: "Peck Deck Fly", target: "15 X3" },
        { id: "p2-m-5", order: 5, name: "Cable pushdown (Tricep)", target: "15 X3" },
        { id: "p2-m-6", order: 6, name: "Dumble extension", target: "15 X3" },
        { id: "p2-m-7", order: 7, name: "Dumble kickback", target: "25 X3" },
        { id: "p2-m-8", order: 8, name: "Flying squats", target: "25 X3" },
        { id: "p2-m-9", order: 9, name: "Leg raises", target: "150" },
      ],
      Tuesday: [
        { id: "p2-tu-1", order: 1, name: "Staircases", target: "4 floors X2" },
        { id: "p2-tu-2", order: 2, name: "Dumbbell raise", target: "15 X3 (shoulder)" },
        { id: "p2-tu-3", order: 3, name: "Lateral Dumbbell raise", target: "25 X3 (shoulder)" },
        { id: "p2-tu-4", order: 4, name: "Front Dumbbell Raise", target: "25 X3 (shoulder)" },
        { id: "p2-tu-5", order: 5, name: "Reverse Peck deck fly", target: "25 X3 (shoulder)" },
        { id: "p2-tu-6", order: 6, name: "Elliptical Cross", target: "10 mins full speed", durationSeconds: 600 },
        { id: "p2-tu-7", order: 7, name: "Skipping", target: "100" },
        { id: "p2-tu-8", order: 8, name: "High knee Jump", target: "50" },
        { id: "p2-tu-9", order: 9, name: "Jumping squats", target: "25" },
        { id: "p2-tu-10", order: 10, name: "Skipping", target: "100" },
        { id: "p2-tu-11", order: 11, name: "High knee Jump", target: "50" },
        { id: "p2-tu-12", order: 12, name: "Jumping squats", target: "25" },
        { id: "p2-tu-13", order: 13, name: "Skipping", target: "100" },
        { id: "p2-tu-14", order: 14, name: "High knee Jump", target: "50" },
        { id: "p2-tu-15", order: 15, name: "Jumping squats", target: "25" },
        { id: "p2-tu-16", order: 16, name: "Side squats", target: "25" },
      ],
      Wednesday: [
        { id: "p2-w-1", order: 1, name: "Staircase", target: "X2 (4 floors)" },
        { id: "p2-w-2", order: 2, name: "Lat pull down", target: "15 X3" },
        { id: "p2-w-3", order: 3, name: "Rowing", target: "15 X3" },
        { id: "p2-w-4", order: 4, name: "Barbell curl", target: "25 X3" },
        { id: "p2-w-5", order: 5, name: "Dumbbell hammer", target: "15 X3" },
        { id: "p2-w-6", order: 6, name: "Dumbbell curl", target: "15 X3" },
        { id: "p2-w-7", order: 7, name: "Jumping squats", target: "25" },
        { id: "p2-w-8", order: 8, name: "Side squats", target: "25" },
        { id: "p2-w-9", order: 9, name: "Leg raises", target: "50" },
        { id: "p2-w-10", order: 10, name: "Jumping squats", target: "25" },
        { id: "p2-w-11", order: 11, name: "Side squats", target: "25" },
        { id: "p2-w-12", order: 12, name: "Leg raises", target: "50" },
        { id: "p2-w-13", order: 13, name: "Jumping squats", target: "25" },
        { id: "p2-w-14", order: 14, name: "Side squats", target: "25" },
        { id: "p2-w-15", order: 15, name: "Leg raises", target: "50" },
      ],
      Thursday: [
        { id: "p2-th-1", order: 1, name: "Elliptical cross", target: "5 mins", durationSeconds: 300 },
        { id: "p2-th-2", order: 2, name: "Staircase", target: "4 floors X2" },
        { id: "p2-th-3", order: 3, name: "Skipping", target: "100" },
        { id: "p2-th-4", order: 4, name: "Jumping jacks", target: "50" },
        { id: "p2-th-5", order: 5, name: "High knee", target: "50" },
        { id: "p2-th-6", order: 6, name: "Jumping Squats", target: "25" },
        { id: "p2-th-7", order: 7, name: "Side squats", target: "50" },
        { id: "p2-th-8", order: 8, name: "Leg raises", target: "50" },
        { id: "p2-th-9", order: 9, name: "Skipping", target: "100" },
        { id: "p2-th-10", order: 10, name: "Staircase", target: "4 floors X2" },
        { id: "p2-th-11", order: 11, name: "Jumping jacks", target: "50" },
        { id: "p2-th-12", order: 12, name: "High knee", target: "50" },
        { id: "p2-th-13", order: 13, name: "Jumping Squats", target: "25" },
        { id: "p2-th-14", order: 14, name: "Side squats", target: "50" },
        { id: "p2-th-15", order: 15, name: "Leg raises", target: "50" },
        { id: "p2-th-16", order: 16, name: "Skipping", target: "100" },
        { id: "p2-th-17", order: 17, name: "Staircase", target: "4 floors X2" },
        { id: "p2-th-18", order: 18, name: "Jumping jacks", target: "50" },
        { id: "p2-th-19", order: 19, name: "High knee", target: "50" },
        { id: "p2-th-20", order: 20, name: "Jumping Squats", target: "25" },
        { id: "p2-th-21", order: 21, name: "Side squats", target: "50" },
        { id: "p2-th-22", order: 22, name: "Leg raises", target: "50" },
        { id: "p2-th-23", order: 23, name: "Jumping Squats", target: "25" },
        { id: "p2-th-24", order: 24, name: "Side squats", target: "50" },
        { id: "p2-th-25", order: 25, name: "Leg raises", target: "50" },
        { id: "p2-th-26", order: 26, name: "Plank Hold", target: "1 min", durationSeconds: 60 },
        { id: "p2-th-27", order: 27, name: "Jumping Squats", target: "25" },
        { id: "p2-th-28", order: 28, name: "Side squats", target: "50" },
        { id: "p2-th-29", order: 29, name: "Leg raises", target: "50" },
        { id: "p2-th-30", order: 30, name: "Plank hold", target: "1 min", durationSeconds: 60 },
      ],
      Friday: [
        { id: "p2-f-1", order: 1, name: "Staircases", target: "4 floors X2" },
        { id: "p2-f-2", order: 2, name: "Squats", target: "25 X2" },
        { id: "p2-f-3", order: 3, name: "Jumping Squats", target: "25 X2" },
        { id: "p2-f-4", order: 4, name: "Leg Curl", target: "25 X4" },
        { id: "p2-f-5", order: 5, name: "Reverse leg curl", target: "25 X3" },
        { id: "p2-f-6", order: 6, name: "Walking Lunges", target: "90" },
        { id: "p2-f-7", order: 7, name: "Jumping squats", target: "25" },
        { id: "p2-f-8", order: 8, name: "Leg raises", target: "30" },
        { id: "p2-f-9", order: 9, name: "Side squats", target: "25" },
        { id: "p2-f-10", order: 10, name: "Jumping squats", target: "25" },
        { id: "p2-f-11", order: 11, name: "Leg raises", target: "30" },
        { id: "p2-f-12", order: 12, name: "Side squats", target: "25" },
        { id: "p2-f-13", order: 13, name: "Jumping squats", target: "25" },
        { id: "p2-f-14", order: 14, name: "Leg raises", target: "30" },
        { id: "p2-f-15", order: 15, name: "Side squats", target: "25" },
        { id: "p2-f-16", order: 16, name: "Calf raises", target: "50" },
      ],
    },
  },
  {
    id: "plan-3",
    name: "Workout Plan 3",
    description: "High-density volume, heavy chest/triceps routines, and 5-lap running blocks",
    days: {
      Monday: [
        { id: "p3-m-1", order: 1, name: "Staircase", target: "4 Floors X2" },
        { id: "p3-m-2", order: 2, name: "Inclined bench press", target: "20 X3" },
        { id: "p3-m-3", order: 3, name: "Flat benchpress", target: "20 X3" },
        { id: "p3-m-4", order: 4, name: "Peck Deck Fly", target: "20 X3" },
        { id: "p3-m-5", order: 5, name: "Cable pushdown (Tricep)", target: "20 X3" },
        { id: "p3-m-6", order: 6, name: "Dumble extension", target: "20 X3" },
        { id: "p3-m-7", order: 7, name: "Dumble kickback", target: "20 X3" },
        { id: "p3-m-8", order: 8, name: "Flying squats", target: "25 X3" },
        { id: "p3-m-9", order: 9, name: "Leg raises", target: "25 X3" },
        { id: "p3-m-10", order: 10, name: "Side squats", target: "25 X3" },
      ],
      Tuesday: [
        { id: "p3-tu-1", order: 1, name: "Skipping", target: "X100" },
        { id: "p3-tu-2", order: 2, name: "Staircase", target: "X1" },
        { id: "p3-tu-3", order: 3, name: "Jumping Jacks", target: "X50" },
        { id: "p3-tu-4", order: 4, name: "Running High knee jump", target: "X2 Rounds" },
        { id: "p3-tu-5", order: 5, name: "Pushups", target: "X20" },
        { id: "p3-tu-6", order: 6, name: "Skipping", target: "X100" },
        { id: "p3-tu-7", order: 7, name: "Staircase", target: "X1" },
        { id: "p3-tu-8", order: 8, name: "Jumping Jacks", target: "X50" },
        { id: "p3-tu-9", order: 9, name: "Running High knee jump", target: "X2 Rounds" },
        { id: "p3-tu-10", order: 10, name: "Pushups", target: "X20" },
        { id: "p3-tu-11", order: 11, name: "Break", target: "2 mins", durationSeconds: 120, isRest: true },
        { id: "p3-tu-12", order: 12, name: "Skipping", target: "X100" },
        { id: "p3-tu-13", order: 13, name: "Staircase", target: "X1" },
        { id: "p3-tu-14", order: 14, name: "Jumping Jacks", target: "X50" },
        { id: "p3-tu-15", order: 15, name: "Running High knee jump", target: "X2 Rounds" },
        { id: "p3-tu-16", order: 16, name: "Pushups", target: "X20" },
        { id: "p3-tu-17", order: 17, name: "5 Laps run (full ground)", target: "5 laps" },
        { id: "p3-tu-18", order: 18, name: "Jumping squats", target: "X25" },
        { id: "p3-tu-19", order: 19, name: "Side squats", target: "25" },
        { id: "p3-tu-20", order: 20, name: "Leg raises", target: "50" },
        { id: "p3-tu-21", order: 21, name: "Plank hold", target: "1 min", durationSeconds: 60 },
        { id: "p3-tu-22", order: 22, name: "5 Laps run (full ground)", target: "5 laps" },
        { id: "p3-tu-23", order: 23, name: "Jumping squats", target: "X25" },
        { id: "p3-tu-24", order: 24, name: "Side squats", target: "25" },
        { id: "p3-tu-25", order: 25, name: "Leg raises", target: "50" },
        { id: "p3-tu-26", order: 26, name: "Plank hold", target: "1 min", durationSeconds: 60 },
      ],
    },
  },
  {
    id: "plan-4",
    name: "Workout Plan 4",
    description: "Back/shoulders emphasis, angle variations, and cardio staircase intervals",
    days: {
      Monday: [
        { id: "p4-m-1", order: 1, name: "Lat pull down", target: "15 X2" },
        { id: "p4-m-2", order: 2, name: "Rowing", target: "15 X2" },
        { id: "p4-m-3", order: 3, name: "Shoulder press", target: "15 X2" },
        { id: "p4-m-4", order: 4, name: "Lateral shoulder press", target: "15 X2" },
        { id: "p4-m-5", order: 5, name: "Front Raise", target: "15 X2" },
        { id: "p4-m-6", order: 6, name: "Dumbbell Internal Rotation", target: "25 X2" },
        { id: "p4-m-7", order: 7, name: "Skipping", target: "100" },
        { id: "p4-m-8", order: 8, name: "Treadmill", target: "10 mins at 5.2 km/h", durationSeconds: 600 },
      ],
      Tuesday: [
        { id: "p4-tu-1", order: 1, name: "Inclined benchpress", target: "120°" },
        { id: "p4-tu-2", order: 2, name: "Flat benchpress", target: "90°" },
        { id: "p4-tu-3", order: 3, name: "Pec deck fly", target: "Target" },
        { id: "p4-tu-4", order: 4, name: "Dumble extension", target: "Target" },
        { id: "p4-tu-5", order: 5, name: "Wired pushdow", target: "Target" },
        { id: "p4-tu-6", order: 6, name: "Wall pushups", target: "Target" },
        { id: "p4-tu-7", order: 7, name: "Skipping", target: "Target" },
      ],
      Wednesday: [
        { id: "p4-w-1", order: 1, name: "Elliptical Cross", target: "5mins", durationSeconds: 300 },
        { id: "p4-w-2", order: 2, name: "Staircase", target: "4 Floors" },
        { id: "p4-w-3", order: 3, name: "Skipping", target: "100" },
        { id: "p4-w-4", order: 4, name: "Pushups", target: "20" },
        { id: "p4-w-5", order: 5, name: "Jumping Jacks", target: "20" },
        { id: "p4-w-6", order: 6, name: "High knee Jump walking", target: "2 Round" },
        { id: "p4-w-7", order: 7, name: "On Spot jumping", target: "15" },
        { id: "p4-w-8", order: 8, name: "Laps Running", target: "2 rounds ground" },
        { id: "p4-w-9", order: 9, name: "Jumping Jacks", target: "15" },
        { id: "p4-w-10", order: 10, name: "On Spot jumping", target: "10" },
        { id: "p4-w-11", order: 11, name: "Pushups", target: "15" },
        { id: "p4-w-12", order: 12, name: "Fast Running", target: "2 Rounds" },
        { id: "p4-w-13", order: 13, name: "Jumping Jacks", target: "10" },
        { id: "p4-w-14", order: 14, name: "High knee Jump walking", target: "1 Round" },
        { id: "p4-w-15", order: 15, name: "On Spot jumping", target: "10" },
        { id: "p4-w-16", order: 16, name: "Pushups", target: "10" },
        { id: "p4-w-17", order: 17, name: "Jumping Jacks", target: "10" },
        { id: "p4-w-18", order: 18, name: "On Spot jumping", target: "10" },
        { id: "p4-w-19", order: 19, name: "Elliptical Cross", target: "10 mins", durationSeconds: 600 },
      ],
    },
  },
];

export const ORDERED_WEEKDAYS: DayOfWeekName[] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

/**
 * Returns today's weekday name if Monday-Friday, else defaults to Monday.
 */
export function getTodayDayName(now: Date = new Date()): DayOfWeekName {
  const dayIndex = now.getDay(); // 0 = Sunday, 1 = Monday, ..., 5 = Friday, 6 = Saturday
  switch (dayIndex) {
    case 1:
      return "Monday";
    case 2:
      return "Tuesday";
    case 3:
      return "Wednesday";
    case 4:
      return "Thursday";
    case 5:
      return "Friday";
    default:
      return "Monday";
  }
}

export function getWorkoutPlan(planId: string): WorkoutPlan {
  return WORKOUT_PLANS.find((p) => p.id === planId) || WORKOUT_PLANS[0];
}

export function getWorkoutExercises(planId: string, day: DayOfWeekName): ExerciseItem[] {
  const plan = getWorkoutPlan(planId);
  return plan.days[day] || [];
}
